### ISSUE TITLE
Ask for password not at start, but at send

### ISSUE THREAD

**Issue by karelbilek** [ksedgwic/Wallet32#12]
I think it would be better to ask for password not at the start of the application, but only when actually sending bitcoins.

It would be much safer. You can see your payments without the need of the private key.

On the other hand, right now, anyone can steal your phone when the app is running and send all the money away, with no need of password. While the seed is protected by password, the bitcoins can still be sent away.

**Comment by dabura667** [comment]
+1 this. Leaving the app open to sending is dangerous. If you send multiple times, you should require inputting the password everytime as default. Maybe relegate the "one time password only" as an optional feature with a warning.

**Comment by karelbilek** [comment]
As I am looking at the source, this will require quite a lot of refractoring.

Basically everything depends on HDWallet here - https://github.com/ksedgwic/Wallet32/blob/master/src/com/bonsai/wallet32/HDWallet.java - that includes all the private keys.

Both the "public" and "private" operations depend on this. (If I understand the code right - I might not since I am only skimming it.)

**Comment by ksedgwic** [comment]
Yes, it would be a bit of work to factor HDWallet into secure and less-secure components.

What if Wallet32 logged itself out after a few minutes of inactivity (configurable)?  This wouldn't be too hard to implement and would seem improve the situation quite a bit.

Also, as we move forward to support connected Trezor use, the factoring becomes much easier.  Basically Wallet32 in Trezor mode is a watch-only wallet, and doesn't even contain the secret parts of the HD hierarchy.  I think this is almost exactly the same split ...

**Comment by karelbilek** [comment]
Yes, it's exactly the same split.

I am not sure what are you trying to say though. I don't think Trezor use should be mandatory.

**Comment by karelbilek** [comment]
The automatic logout would be a nice "hot-fix" though

**Comment by dabura667** [comment]
yeah, I would say automatic logout after a few minutes of idle + Warning message on password input screen. + if you leave the app and return to home screen etc. it automatically logs out.

The last one is very good, because if you have to leave your phone, you can just hit the home button and when the app goes into the background it automatically logs out.

**Comment by ksedgwic** [comment]
I've implemented a simple configurable background timeout.  When the app is not in the foreground it times out and terminates after a period (default 10 min).

It's in version 0.3.5, pushed to the alpha channel just now.

**Comment by slush0** [comment]
FYI mytrezor solves passphrase handling by asking for passphrase on wallet initialization (=once) and then only when private keys are used (=on send), but it internally stores hash of used password, so application can easily detect that passphrases provided during initialization and during send differs. This is important, otherwise using another passphrase for each action will result in strange errors.
